// Ported from the 0.13.0 suite: `automatic semicolons` (formatter).
//
// Verdict: 3 changed on purpose, 1 deleted as a bug.
//
// 2 × 0.13 collapsed groups the source had spread:
//   - [1] line 1: 0.13 "if () {} else {};" → now "if () {}"
//   - [2] line 1: 0.13 "{}.A;" → now "{}"
//
// 1 × the semicolon rule:
//   - [0] line 1: 0.13 "{};" → now "{}"
//
// 1 case(s) of this name are refusals — the parse throws, so they cannot be
// a fixture here. They are pinned in `tests/refusals/` (see `tests/refusals.test.ts`).
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
{
}
A
