// Ported from the 0.13.0 suite: `double newline after import section` (formatter).
//
// Verdict: 9 already identical to 0.13, 2 changed on purpose.
//
// 1 × the semicolon rule:
//   - [8] line 3: 0.13 "actor {};" → now "actor {}"
//
// 1 × 0.13 expanded groups that fit:
//   - [10] line 5: 0.13 "actor A {" → now "actor A { abc };"
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
__sentinel_279__