// Ported from the 0.13.0 suite: `null coalesce operator` (formatter).
//
// Verdict: 2 already identical to 0.13, 18 changed on purpose.
//
// 18 × `??` spacing:
//   - [0] line 1: 0.13 "a ??b" → now "a ?? b"
//   - [1] line 1: 0.13 "a ??b" → now "a  ??  b"
//   - [2] line 1: 0.13 "a ??b ??c" → now "a ?? b ?? c"
//   - [3] line 1: 0.13 "a ??b;" → now "a"
//   - [4] line 2: 0.13 "a ??b" → now "a"
//   - [7] line 1: 0.13 "??a" → now "? ?a"
//   - [8] line 1: 0.13 "a ???b" → now "a ?? ?b"
//   - [9] line 1: 0.13 "?a ??b" → now "?a ?? b"
//   - [10] line 1: 0.13 "?a ???b" → now "?a ?? ?b"
//   - [11] line 1: 0.13 "??a ??b" → now "??a ?? b"
//   - [12] line 1: 0.13 "a ????b" → now "a ?? ??b"
//   - [13] line 1: 0.13 "(a) ??b" → now "(a) ?? b"
//   - [14] line 1: 0.13 "a ??(b)" → now "a ?? (b)"
//   - [15] line 1: 0.13 "(a) ??(b)" → now "(a) ?? (b)"
//   - [16] line 1: 0.13 "(a ??b) ??c" → now "(a ?? b) ?? c"
//   - [17] line 1: 0.13 "a ??(b ??c)" → now "a ?? (b ?? c)"
//   - [18] line 1: 0.13 "(?a) ??b" → now "(?a) ?? b"
//   - [19] line 1: 0.13 "a ??(?b)" → now "a ?? (?b)"
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
(a) ?? b
