// Ported from the 0.13.0 suite: `pipe operator` (formatter).
//
// Verdict: 2 changed on purpose.
//
// 2 × 0.13 expanded groups that fit:
//   - [0] line 1: 0.13 "A" → now "A |> B"
//   - [1] line 1: 0.13 "(" → now "(A |> B)"
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
A
|> B
(A
|> B)