// Ported from the 0.13.0 suite: `prettier-ignore` (formatter).
//
// Verdict: 1 already identical to 0.13, 2 changed on purpose, 1 deleted as a bug.
//
// 2 × breaks placed differently:
//   - [0] line 3: 0.13 "2 * 2;" → now "2*2"
//   - [1] line 4: 0.13 "2 * 2;" → now "2*2"
//
// 1 case(s) of this name are refusals — the parse throws, so they cannot be
// a fixture here. They are pinned in `tests/refusals/` (see `tests/refusals.test.ts`).
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
//prettier-ignore
1*1;
2*2
//prettier-ignore
1*1;

2*2
// prettier-ignore
{
abc}