// Ported from the 0.13.0 suite: `subtraction vs. negative number` (formatter).
//
// Verdict: 5 already identical to 0.13, 8 changed on purpose.
//
// 7 × breaks placed differently:
//   - [6] line 1: 0.13 "1 - 1" → now "1-1"
//   - [7] line 1: 0.13 "1.0 - 1.0" → now "1.0-1.0"
//   - [8] line 1: 0.13 "x - 1" → now "x-1"
//   - [9] line 1: 0.13 "x - 1.0" → now "x-1.0"
//   - [10] line 1: 0.13 "x + -1" → now "x+ -1"
//   - [11] line 1: 0.13 "1 - 1" → now "1 -1"
//   - [12] line 1: 0.13 "x - 1" → now "x -1"
//
// 1 × 0.13 collapsed groups the source had spread:
//   - [3] line 1: 0.13 "x; -1" → now "x;"
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
1 - 1

x - 1

x + -1

x; -1

x(-1)

return -1

1-1
1.0-1.0
x-1
x-1.0
x+ -1
1 -1
x -1