// Ported from the 0.13.0 suite: `trailing comma in square brackets` (formatter).
//
// Verdict: 4 changed on purpose, 5 deleted as a bug.
//
// 3 × 0.13 expanded groups that fit:
//   - [0] line 1: 0.13 "[" → now "[a, b]"
//   - [1] line 1: 0.13 "[" → now "[a,]"
//   - [7] line 1: 0.13 "let x = [" → now "let x = [{ abc; },];"
//
// 1 × breaks placed differently:
//   - [2] line 2: 0.13 "T" → now "T"
//
// 5 case(s) of this name are refusals — the parse throws, so they cannot be
// a fixture here. They are pinned in `tests/refusals/` (see `tests/refusals.test.ts`).
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
[
a,]