// Ported from the 0.13.0 suite: `type bindings` (formatter).
//
// Verdict: 2 changed on purpose.
//
// 2 × breaks placed differently:
//   - [0] line 1: 0.13 "func foo<A <: Any>(x : A) {}" → now "func foo<A<:Any>(x:A) {}"
//   - [1] line 1: 0.13 "func foo<A <: Any>(x : A) {}" → now "func foo <A <: Any>(x:A) {}"
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
func foo <A <: Any>(x:A) {}