// Ported from the 0.13.0 suite: `wildcard identifier` (formatter).
//
// Verdict: 6 already identical to 0.13, 2 changed on purpose.
//
// 2 × breaks placed differently:
//   - [2] line 1: 0.13 "_(i)" → now "_ (i)"
//   - [3] line 1: 0.13 "_[i]" → now "_ [i]"
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
_(i)
