/**
 * Lazy, memoised initialisation of web-tree-sitter and the pinned Motoko grammar.
 *
 * `web-tree-sitter` is pinned exactly (see package.json) because a minor bump can change ABI
 * compatibility, and the grammar was generated by a specific tree-sitter-cli. The grammar package
 * itself is a devDependency we only use to *generate* types and to obtain the wasm; the wasm we
 * load is the copy vendored next to this file at build time, so plugin users never run
 * `node-gyp-build` and never need a native toolchain.
 *
 * Both wasm files are loaded through `locateFile`-style explicit paths rather than by URL, because
 * the plugin must work identically in Node, in a browser bundle and inside a Node SEA binary, and
 * only an explicit path lets the build step place the assets.
 */

import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Parser, Language } from 'web-tree-sitter';

/** Resolved at module load: the directory holding this module once built. */
const here = dirname(fileURLToPath(import.meta.url));

/**
 * The vendored grammar wasm, and the web-tree-sitter runtime wasm it needs.
 *
 * `tools/build-copy-assets.mjs` copies both next to the compiled `parser/` output, so these
 * relative names hold in `lib/parser/` exactly as they do in `src/parser/`.
 */
const GRAMMAR_WASM = join(here, 'tree-sitter-motoko.wasm');

/**
 * Locate web-tree-sitter's own runtime wasm.
 *
 * In a plain Node install it sits at the package root. Under a bundler or a SEA build the package
 * may not be resolvable, so the vendored copy next to this file is tried first and the package
 * resolution is the fallback. Building that copy is the build step's job.
 */
function runtimeWasmCandidates(): string[] {
    const vendored = join(here, 'web-tree-sitter.wasm');
    try {
        const require = createRequire(import.meta.url);
        const pkg = require.resolve('web-tree-sitter/package.json');
        return [vendored, join(dirname(pkg), 'web-tree-sitter.wasm')];
    } catch {
        return [vendored];
    }
}

/** Memoised: one init per process, shared by every format call. */
let initPromise: Promise<Language> | null = null;

/**
 * Initialise the wasm runtime and load the language. Safe to call concurrently and repeatedly;
 * the work happens once. Rejects if it fails, so a caller never proceeds with a half-built parser.
 */
async function loadLanguage() {
    // Parser.init() loads the web-tree-sitter runtime wasm. Passing `locateFile` lets us point at
    // the vendored copy so the load does not depend on the module resolver finding the package.
    let runtimePath = null;
    for (const candidate of runtimeWasmCandidates()) {
        try {
            await readFile(candidate);
            runtimePath = candidate;
            break;
        } catch {
            // Try the next candidate; if none exist, fall back to the default locate behaviour and
            // let the error surface from the runtime itself rather than from this probe.
        }
    }

    await Parser.init(
        runtimePath
            ? {
                  locateFile: (name: string) =>
                      name.endsWith('.wasm') ? runtimePath : name,
              }
            : undefined,
    );

    // Language.load accepts a Uint8Array, so read the grammar ourselves rather than relying on the
    // runtime's own fetch, which is not available inside a SEA binary.
    const grammarBytes = await readFile(GRAMMAR_WASM);
    return Language.load(grammarBytes);
}

/**
 * A parser with the Motoko grammar installed, plus the language itself.
 *
 * `Parser` instances hold wasm memory and are not documented as reentrant, so callers get a fresh
 * one per parse and are expected to `delete()` it. Only the expensive part — runtime init and
 * language compilation — is shared.
 */
let languagePromise: Promise<Language> | null = null;

/** The compiled grammar. The first call pays for init; every later call awaits the same promise. */
export function getLanguage() {
    if (!languagePromise) {
        languagePromise = loadLanguage();
        // A failed init must not be cached, or every later call inherits the same rejection without
        // a chance to retry (e.g. after a transient read failure on a fresh checkout).
        languagePromise.catch(() => {
            languagePromise = null;
        });
    }
    return languagePromise;
}

/** A new parser bound to the Motoko grammar. The caller must `delete()` it. */
export async function createParser() {
    if (!initPromise) {
        initPromise = getLanguage();
        initPromise.catch(() => {
            initPromise = null;
        });
    }
    const language = await initPromise;
    const parser = new Parser();
    parser.setLanguage(language);
    return parser;
}

/** The ABI version of the loaded grammar, for diagnostics and the corpus report. Useful for
 * confirming the vendored wasm is the one the build intended. */
export async function grammarInfo() {
    const language = await getLanguage();
    const metadata = language.metadata;
    return {
        abiVersion: language.abiVersion,
        name: language.name,
        version: metadata
            ? `${metadata.major_version}.${metadata.minor_version}.${metadata.patch_version}`
            : null,
        nodeTypeCount: language.nodeTypeCount,
    };
}

/** For tests and the corpus harness: forget the memoised language. Never called in production. */
export function _resetForTests() {
    languagePromise = null;
    initPromise = null;
}
