// Ported from the 0.13.0 suite: `import with missing semicolon at end` (organizeImports).
//
// Verdict: 1 changed on purpose.
//
// 1 × 0.13 collapsed groups the source had spread:
//   - [0] line 1: 0.13 "import Array \"mo:base/Array\";" → now "import Array \"mo:base/Array\""
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
import Array "mo:base/Array"
import Text "mo:base/Text";

actor {}