// Ported from the 0.13.0 suite: `preserve spacing between imports and code` (organizeImports).
//
// Verdict: 1 changed on purpose.
//
// 1 × 0.13 expanded groups that fit:
//   - [0] line 6: 0.13 "actor {" → now "actor { public func test() {} }"
//
// The body below is the legacy input byte-for-byte; the snapshot records what the
// printer does to it, and `tests/format.test.ts` also asserts it is a fixed point.
// Generated by `tools/port-fixtures.mts`; edit that, not this file.
import Array "mo:base/Array";
import Text "mo:base/Text";


// Main actor
actor {
  public func test() {}
}